name: ublue-qtile
description: Fedora 44 image with Qtile WM + SDDM (bazzite base, KDE stripped)
base-image: ghcr.io/ublue-os/bazzite
image-version: latest
modules:
- type: files
  files:
  - source: system
    destination: /
- type: script
  snippets:
  - xargs -a /usr/share/ublue-qtile/remove-packages.txt dnf -y remove --setopt=tsflags=noscripts
- type: dnf
  repos:
    files:
    - https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
    copr:
    - scottames/ghostty
    - tokariew/i3lock-color
  install:
    packages:
    - aisleriot
    - blueman
    - brave-origin
    - brightnessctl
    - dunst
    - feh
    - geany
    - ghostty
    - git
    - gstreamer1-plugins-ugly
    - gstreamer1-vaapi
    - i3lock-color
    - lxpolkit
    - mpv
    - nemo
    - network-manager-applet
    - papirus-icon-theme
    - pavucontrol
    - picom
    - python3-xcffib
    - qt5ct
    - qt6-qt5compat
    - qt6ct
    - qtile
    - qtile-extras
    - remmina
    - ripgrep
    - scrot
    - sddm
    - tlp
    - xautolock
    - xorg-x11-drv-evdev
    - xorg-x11-drv-libinput
    - xorg-x11-server-Xorg
    - xset
  remove:
    packages: []
- type: systemd
  system:
    enabled:
    - tlp.service
- type: default-flatpaks
  configurations:
  - notify: true
    scope: system
    repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
    repo-name: flathub
    install:
    - com.vysp3r.ProtonPlus
  - scope: user
    repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
    repo-name: flathub
- type: script
  snippets:
  - curl -sL -o /tmp/topgrade.tar.gz https://github.com/topgrade-rs/topgrade/releases/download/v17.9.0/topgrade-v17.9.0-x86_64-unknown-linux-gnu.tar.gz && tar -xzf /tmp/topgrade.tar.gz -C /usr/bin topgrade
    && chmod +x /usr/bin/topgrade
  - rm -rf /tmp/topgrade.tar.gz /tmp/system_files
- type: signing
