[Autologin]
# Uncomment and set to auto-login (optional)
# User=lee
# Session=qtile-wayland.desktop

[Theme]
Current=breeze
CursorTheme=breeze_cursors

[Users]
MaximumUsers=1

[General]
HaltCommand=/usr/bin/systemctl poweroff
RebootCommand=/usr/bin/systemctl reboot
DefaultSession=qtile-wayland.desktop
